/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.Keys;
import ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.Public;
import ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.tables.CompilationEvents.CompilationEventsPath;
import ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.tables.Events.EventsPath;
import ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.tables.records.CompilationsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Compilations extends TableImpl<CompilationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.compilations</code>
     */
    public static final Compilations COMPILATIONS = new Compilations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompilationsRecord> getRecordType() {
        return CompilationsRecord.class;
    }

    /**
     * The column <code>public.compilations.id</code>.
     */
    public final TableField<CompilationsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.compilations.title</code>.
     */
    public final TableField<CompilationsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.compilations.pinned</code>.
     */
    public final TableField<CompilationsRecord, Boolean> PINNED = createField(DSL.name("pinned"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Compilations(Name alias, Table<CompilationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Compilations(Name alias, Table<CompilationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.compilations</code> table reference
     */
    public Compilations(String alias) {
        this(DSL.name(alias), COMPILATIONS);
    }

    /**
     * Create an aliased <code>public.compilations</code> table reference
     */
    public Compilations(Name alias) {
        this(alias, COMPILATIONS);
    }

    /**
     * Create a <code>public.compilations</code> table reference
     */
    public Compilations() {
        this(DSL.name("compilations"), null);
    }

    public <O extends Record> Compilations(Table<O> path, ForeignKey<O, CompilationsRecord> childPath, InverseForeignKey<O, CompilationsRecord> parentPath) {
        super(path, childPath, parentPath, COMPILATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CompilationsPath extends Compilations implements Path<CompilationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CompilationsPath(Table<O> path, ForeignKey<O, CompilationsRecord> childPath, InverseForeignKey<O, CompilationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CompilationsPath(Name alias, Table<CompilationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CompilationsPath as(String alias) {
            return new CompilationsPath(DSL.name(alias), this);
        }

        @Override
        public CompilationsPath as(Name alias) {
            return new CompilationsPath(alias, this);
        }

        @Override
        public CompilationsPath as(Table<?> alias) {
            return new CompilationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CompilationsRecord, Long> getIdentity() {
        return (Identity<CompilationsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CompilationsRecord> getPrimaryKey() {
        return Keys.PK_COMPILATIONS;
    }

    @Override
    public List<UniqueKey<CompilationsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_COMPILATIONS_TITLE);
    }

    private transient CompilationEventsPath _compilationEvents;

    /**
     * Get the implicit to-many join path to the
     * <code>public.compilation_events</code> table
     */
    public CompilationEventsPath compilationEvents() {
        if (_compilationEvents == null)
            _compilationEvents = new CompilationEventsPath(this, null, Keys.COMPILATION_EVENTS__FK_COMPILATION_EVENTS_COMPILATION.getInverseKey());

        return _compilationEvents;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.events</code>
     * table
     */
    public EventsPath events() {
        return compilationEvents().events();
    }

    @Override
    public Compilations as(String alias) {
        return new Compilations(DSL.name(alias), this);
    }

    @Override
    public Compilations as(Name alias) {
        return new Compilations(alias, this);
    }

    @Override
    public Compilations as(Table<?> alias) {
        return new Compilations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Compilations rename(String name) {
        return new Compilations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Compilations rename(Name name) {
        return new Compilations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Compilations rename(Table<?> name) {
        return new Compilations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Compilations where(Condition condition) {
        return new Compilations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Compilations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Compilations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Compilations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Compilations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Compilations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Compilations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Compilations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Compilations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Compilations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
