/*
 * This file is generated by jOOQ.
 */
package ru.explorewithme.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.explorewithme.jooq.Keys;
import ru.explorewithme.jooq.Public;
import ru.explorewithme.jooq.tables.Events.EventsPath;
import ru.explorewithme.jooq.tables.Users.UsersPath;
import ru.explorewithme.jooq.tables.records.RequestsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Requests extends TableImpl<RequestsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.requests</code>
     */
    public static final Requests REQUESTS = new Requests();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RequestsRecord> getRecordType() {
        return RequestsRecord.class;
    }

    /**
     * The column <code>public.requests.id</code>.
     */
    public final TableField<RequestsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.requests.created</code>.
     */
    public final TableField<RequestsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.requests.event_id</code>.
     */
    public final TableField<RequestsRecord, Long> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.requests.requester</code>.
     */
    public final TableField<RequestsRecord, Long> REQUESTER = createField(DSL.name("requester"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.requests.status</code>.
     */
    public final TableField<RequestsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(31).nullable(false), this, "");

    private Requests(Name alias, Table<RequestsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Requests(Name alias, Table<RequestsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.requests</code> table reference
     */
    public Requests(String alias) {
        this(DSL.name(alias), REQUESTS);
    }

    /**
     * Create an aliased <code>public.requests</code> table reference
     */
    public Requests(Name alias) {
        this(alias, REQUESTS);
    }

    /**
     * Create a <code>public.requests</code> table reference
     */
    public Requests() {
        this(DSL.name("requests"), null);
    }

    public <O extends Record> Requests(Table<O> path, ForeignKey<O, RequestsRecord> childPath, InverseForeignKey<O, RequestsRecord> parentPath) {
        super(path, childPath, parentPath, REQUESTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RequestsPath extends Requests implements Path<RequestsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RequestsPath(Table<O> path, ForeignKey<O, RequestsRecord> childPath, InverseForeignKey<O, RequestsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RequestsPath(Name alias, Table<RequestsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RequestsPath as(String alias) {
            return new RequestsPath(DSL.name(alias), this);
        }

        @Override
        public RequestsPath as(Name alias) {
            return new RequestsPath(alias, this);
        }

        @Override
        public RequestsPath as(Table<?> alias) {
            return new RequestsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RequestsRecord, Long> getIdentity() {
        return (Identity<RequestsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RequestsRecord> getPrimaryKey() {
        return Keys.PK_REQUESTS;
    }

    @Override
    public List<ForeignKey<RequestsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REQUESTS__FK_REQUESTS_EVENT, Keys.REQUESTS__FK_REQUESTS_REQUESTER);
    }

    private transient EventsPath _events;

    /**
     * Get the implicit join path to the <code>public.events</code> table.
     */
    public EventsPath events() {
        if (_events == null)
            _events = new EventsPath(this, Keys.REQUESTS__FK_REQUESTS_EVENT, null);

        return _events;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.REQUESTS__FK_REQUESTS_REQUESTER, null);

        return _users;
    }

    @Override
    public Requests as(String alias) {
        return new Requests(DSL.name(alias), this);
    }

    @Override
    public Requests as(Name alias) {
        return new Requests(alias, this);
    }

    @Override
    public Requests as(Table<?> alias) {
        return new Requests(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Requests rename(String name) {
        return new Requests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Requests rename(Name name) {
        return new Requests(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Requests rename(Table<?> name) {
        return new Requests(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Requests where(Condition condition) {
        return new Requests(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Requests where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Requests where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Requests where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Requests where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Requests where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Requests where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Requests where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Requests whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Requests whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
