/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.practicum.explorewithme.jooq.tables.Categories;
import ru.practicum.explorewithme.jooq.tables.CompilationEvents;
import ru.practicum.explorewithme.jooq.tables.Compilations;
import ru.practicum.explorewithme.jooq.tables.Databasechangeloglock;
import ru.practicum.explorewithme.jooq.tables.Events;
import ru.practicum.explorewithme.jooq.tables.Locations;
import ru.practicum.explorewithme.jooq.tables.Requests;
import ru.practicum.explorewithme.jooq.tables.Users;
import ru.practicum.explorewithme.jooq.tables.records.CategoriesRecord;
import ru.practicum.explorewithme.jooq.tables.records.CompilationEventsRecord;
import ru.practicum.explorewithme.jooq.tables.records.CompilationsRecord;
import ru.practicum.explorewithme.jooq.tables.records.DatabasechangeloglockRecord;
import ru.practicum.explorewithme.jooq.tables.records.EventsRecord;
import ru.practicum.explorewithme.jooq.tables.records.LocationsRecord;
import ru.practicum.explorewithme.jooq.tables.records.RequestsRecord;
import ru.practicum.explorewithme.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoriesRecord> PK_CATEGORIES = Internal.createUniqueKey(Categories.CATEGORIES, DSL.name("pk_categories"), new TableField[] { Categories.CATEGORIES.ID }, true);
    public static final UniqueKey<CategoriesRecord> UQ_CATEGORIES_NAME = Internal.createUniqueKey(Categories.CATEGORIES, DSL.name("uq_categories_name"), new TableField[] { Categories.CATEGORIES.NAME }, true);
    public static final UniqueKey<CompilationEventsRecord> PK_COMPILATION_EVENTS = Internal.createUniqueKey(CompilationEvents.COMPILATION_EVENTS, DSL.name("pk_compilation_events"), new TableField[] { CompilationEvents.COMPILATION_EVENTS.COMPILATION_ID, CompilationEvents.COMPILATION_EVENTS.EVENT_ID }, true);
    public static final UniqueKey<CompilationsRecord> PK_COMPILATIONS = Internal.createUniqueKey(Compilations.COMPILATIONS, DSL.name("pk_compilations"), new TableField[] { Compilations.COMPILATIONS.ID }, true);
    public static final UniqueKey<CompilationsRecord> UQ_COMPILATIONS_TITLE = Internal.createUniqueKey(Compilations.COMPILATIONS, DSL.name("uq_compilations_title"), new TableField[] { Compilations.COMPILATIONS.TITLE }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<EventsRecord> PK_EVENTS = Internal.createUniqueKey(Events.EVENTS, DSL.name("pk_events"), new TableField[] { Events.EVENTS.ID }, true);
    public static final UniqueKey<LocationsRecord> PK_LOCATIONS = Internal.createUniqueKey(Locations.LOCATIONS, DSL.name("pk_locations"), new TableField[] { Locations.LOCATIONS.ID }, true);
    public static final UniqueKey<RequestsRecord> PK_REQUESTS = Internal.createUniqueKey(Requests.REQUESTS, DSL.name("pk_requests"), new TableField[] { Requests.REQUESTS.ID }, true);
    public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("pk_users"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> UQ_USERS_EMAIL = Internal.createUniqueKey(Users.USERS, DSL.name("uq_users_email"), new TableField[] { Users.USERS.EMAIL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CompilationEventsRecord, CompilationsRecord> COMPILATION_EVENTS__FK_COMPILATION_EVENTS_COMPILATION = Internal.createForeignKey(CompilationEvents.COMPILATION_EVENTS, DSL.name("fk_compilation_events_compilation"), new TableField[] { CompilationEvents.COMPILATION_EVENTS.COMPILATION_ID }, Keys.PK_COMPILATIONS, new TableField[] { Compilations.COMPILATIONS.ID }, true);
    public static final ForeignKey<CompilationEventsRecord, EventsRecord> COMPILATION_EVENTS__FK_COMPILATION_EVENTS_EVENT = Internal.createForeignKey(CompilationEvents.COMPILATION_EVENTS, DSL.name("fk_compilation_events_event"), new TableField[] { CompilationEvents.COMPILATION_EVENTS.EVENT_ID }, Keys.PK_EVENTS, new TableField[] { Events.EVENTS.ID }, true);
    public static final ForeignKey<EventsRecord, CategoriesRecord> EVENTS__FK_EVENTS_CATEGORY = Internal.createForeignKey(Events.EVENTS, DSL.name("fk_events_category"), new TableField[] { Events.EVENTS.CATEGORY_ID }, Keys.PK_CATEGORIES, new TableField[] { Categories.CATEGORIES.ID }, true);
    public static final ForeignKey<EventsRecord, UsersRecord> EVENTS__FK_EVENTS_INITIATOR = Internal.createForeignKey(Events.EVENTS, DSL.name("fk_events_initiator"), new TableField[] { Events.EVENTS.INITIATOR_ID }, Keys.PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<EventsRecord, LocationsRecord> EVENTS__FK_EVENTS_LOCATION = Internal.createForeignKey(Events.EVENTS, DSL.name("fk_events_location"), new TableField[] { Events.EVENTS.LOCATION_ID }, Keys.PK_LOCATIONS, new TableField[] { Locations.LOCATIONS.ID }, true);
    public static final ForeignKey<RequestsRecord, EventsRecord> REQUESTS__FK_REQUESTS_EVENT = Internal.createForeignKey(Requests.REQUESTS, DSL.name("fk_requests_event"), new TableField[] { Requests.REQUESTS.EVENT_ID }, Keys.PK_EVENTS, new TableField[] { Events.EVENTS.ID }, true);
    public static final ForeignKey<RequestsRecord, UsersRecord> REQUESTS__FK_REQUESTS_REQUESTER = Internal.createForeignKey(Requests.REQUESTS, DSL.name("fk_requests_requester"), new TableField[] { Requests.REQUESTS.REQUESTER }, Keys.PK_USERS, new TableField[] { Users.USERS.ID }, true);
}
