/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.practicum.explorewithme.jooq.tables.Categories;
import ru.practicum.explorewithme.jooq.tables.Comments;
import ru.practicum.explorewithme.jooq.tables.CompilationEvents;
import ru.practicum.explorewithme.jooq.tables.Compilations;
import ru.practicum.explorewithme.jooq.tables.Databasechangelog;
import ru.practicum.explorewithme.jooq.tables.Databasechangeloglock;
import ru.practicum.explorewithme.jooq.tables.Events;
import ru.practicum.explorewithme.jooq.tables.Locations;
import ru.practicum.explorewithme.jooq.tables.Requests;
import ru.practicum.explorewithme.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.comments</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.compilation_events</code>.
     */
    public final CompilationEvents COMPILATION_EVENTS = CompilationEvents.COMPILATION_EVENTS;

    /**
     * The table <code>public.compilations</code>.
     */
    public final Compilations COMPILATIONS = Compilations.COMPILATIONS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.events</code>.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>public.locations</code>.
     */
    public final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>public.requests</code>.
     */
    public final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Categories.CATEGORIES,
            Comments.COMMENTS,
            CompilationEvents.COMPILATION_EVENTS,
            Compilations.COMPILATIONS,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Events.EVENTS,
            Locations.LOCATIONS,
            Requests.REQUESTS,
            Users.USERS
        );
    }
}
