services:
  stats-server:
    build:
      context: .
      dockerfile: stat/server/Dockerfile
    ports:
      - "9090:9090"

  ewm-service:
    build:
      context: ./service
    ports:
      - "8080:8080"