services:
  stats-db:
    image: postgres:16-alpine
    container_name: stats-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  stats-server:
    build:
      context: .
      dockerfile: stat/server/Dockerfile
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  ewm-service:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"