services:
  stats-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  stats-server:
    build:
      context: .
      dockerfile: stat/server/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  ewm-service:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      STATS_SERVER_URL: http://stats-server:9090