services:
  stats-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  ewm-service:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"

  stats-server:
    build:
      context: .
      dockerfile: stat/server/Dockerfile
    ports:
      - "9090:9090"