version: '3.8'

services:
  stats-postgres:
    image: postgres:16-alpine
    container_name: stats-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  stats-server:
    build:
      context: .
      dockerfile: stat/server/Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-postgres

  ewm-service:
    build:
      context: .
      dockerfile: service/Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"