/*
 * This file is generated by jOOQ.
 */
package ru.explorewithme.jooq;


import ru.explorewithme.jooq.tables.Categories;
import ru.explorewithme.jooq.tables.CompilationEvents;
import ru.explorewithme.jooq.tables.Compilations;
import ru.explorewithme.jooq.tables.Events;
import ru.explorewithme.jooq.tables.Locations;
import ru.explorewithme.jooq.tables.Requests;
import ru.explorewithme.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.compilation_events</code>.
     */
    public static final CompilationEvents COMPILATION_EVENTS = CompilationEvents.COMPILATION_EVENTS;

    /**
     * The table <code>public.compilations</code>.
     */
    public static final Compilations COMPILATIONS = Compilations.COMPILATIONS;

    /**
     * The table <code>public.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>public.locations</code>.
     */
    public static final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>public.requests</code>.
     */
    public static final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
