server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/schema.sql


logging:
  level:
    root: TRACE
  org:
    jooq: TRACE
---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
ewm-stat-server:
  url: "http://localhost:9090"

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://service-db:5432/service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
ewm-stat-server:
  url: "http://stats-server:9090"
