CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name VARCHAR(63)                              NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(63)                              NOT NULL,
    email VARCHAR(63)                              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                             NOT NULL,
    pinned BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id),
    CONSTRAINT uq_compilations_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    lat FLOAT                                      NOT NULL,
    lon FLOAT                                      NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000)                            NOT NULL,
    category_id        BIGINT                                   NOT NULL,
    confirmed_requests INTEGER                                  DEFAULT 0,
    created_on         TIMESTAMP                                NOT NULL,
    description        VARCHAR(7000)                            NOT NULL,
    event_date         TIMESTAMP                                NOT NULL,
    initiator_id       BIGINT                                   NOT NULL,
    location_id        BIGINT                                   NOT NULL,
    paid               BOOLEAN                                  DEFAULT false,
    participant_limit  INTEGER                                  DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN                                  DEFAULT true,
    state              VARCHAR(31)                              NOT NULL,
    title              VARCHAR(120)                             NOT NULL,
    views              INTEGER                                  DEFAULT 0,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_category   FOREIGN KEY (category_id)  REFERENCES categories(id),
    CONSTRAINT fk_events_initiator  FOREIGN KEY (initiator_id) REFERENCES users(id),
    CONSTRAINT fk_events_location   FOREIGN KEY (location_id)  REFERENCES locations(id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_compilation_events_event       FOREIGN KEY (event_id)       REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    TIMESTAMP                                NOT NULL,
    event_id   BIGINT                                   NOT NULL,
    requester  BIGINT                                   NOT NULL,
    status     VARCHAR(31)                              NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_event     FOREIGN KEY (event_id)   REFERENCES events(id),
    CONSTRAINT fk_requests_requester FOREIGN KEY (requester)  REFERENCES users(id)
);