/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.practicum.explorewithme.jooq.Keys;
import ru.practicum.explorewithme.jooq.Public;
import ru.practicum.explorewithme.jooq.tables.Compilations.CompilationsPath;
import ru.practicum.explorewithme.jooq.tables.Events.EventsPath;
import ru.practicum.explorewithme.jooq.tables.records.CompilationEventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompilationEvents extends TableImpl<CompilationEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.compilation_events</code>
     */
    public static final CompilationEvents COMPILATION_EVENTS = new CompilationEvents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompilationEventsRecord> getRecordType() {
        return CompilationEventsRecord.class;
    }

    /**
     * The column <code>public.compilation_events.compilation_id</code>.
     */
    public final TableField<CompilationEventsRecord, Long> COMPILATION_ID = createField(DSL.name("compilation_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.compilation_events.event_id</code>.
     */
    public final TableField<CompilationEventsRecord, Long> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private CompilationEvents(Name alias, Table<CompilationEventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CompilationEvents(Name alias, Table<CompilationEventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.compilation_events</code> table reference
     */
    public CompilationEvents(String alias) {
        this(DSL.name(alias), COMPILATION_EVENTS);
    }

    /**
     * Create an aliased <code>public.compilation_events</code> table reference
     */
    public CompilationEvents(Name alias) {
        this(alias, COMPILATION_EVENTS);
    }

    /**
     * Create a <code>public.compilation_events</code> table reference
     */
    public CompilationEvents() {
        this(DSL.name("compilation_events"), null);
    }

    public <O extends Record> CompilationEvents(Table<O> path, ForeignKey<O, CompilationEventsRecord> childPath, InverseForeignKey<O, CompilationEventsRecord> parentPath) {
        super(path, childPath, parentPath, COMPILATION_EVENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CompilationEventsPath extends CompilationEvents implements Path<CompilationEventsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CompilationEventsPath(Table<O> path, ForeignKey<O, CompilationEventsRecord> childPath, InverseForeignKey<O, CompilationEventsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CompilationEventsPath(Name alias, Table<CompilationEventsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CompilationEventsPath as(String alias) {
            return new CompilationEventsPath(DSL.name(alias), this);
        }

        @Override
        public CompilationEventsPath as(Name alias) {
            return new CompilationEventsPath(alias, this);
        }

        @Override
        public CompilationEventsPath as(Table<?> alias) {
            return new CompilationEventsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CompilationEventsRecord> getPrimaryKey() {
        return Keys.PK_COMPILATION_EVENTS;
    }

    @Override
    public List<ForeignKey<CompilationEventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMPILATION_EVENTS__FK_COMPILATION_EVENTS_COMPILATION, Keys.COMPILATION_EVENTS__FK_COMPILATION_EVENTS_EVENT);
    }

    private transient CompilationsPath _compilations;

    /**
     * Get the implicit join path to the <code>public.compilations</code> table.
     */
    public CompilationsPath compilations() {
        if (_compilations == null)
            _compilations = new CompilationsPath(this, Keys.COMPILATION_EVENTS__FK_COMPILATION_EVENTS_COMPILATION, null);

        return _compilations;
    }

    private transient EventsPath _events;

    /**
     * Get the implicit join path to the <code>public.events</code> table.
     */
    public EventsPath events() {
        if (_events == null)
            _events = new EventsPath(this, Keys.COMPILATION_EVENTS__FK_COMPILATION_EVENTS_EVENT, null);

        return _events;
    }

    @Override
    public CompilationEvents as(String alias) {
        return new CompilationEvents(DSL.name(alias), this);
    }

    @Override
    public CompilationEvents as(Name alias) {
        return new CompilationEvents(alias, this);
    }

    @Override
    public CompilationEvents as(Table<?> alias) {
        return new CompilationEvents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompilationEvents rename(String name) {
        return new CompilationEvents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompilationEvents rename(Name name) {
        return new CompilationEvents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompilationEvents rename(Table<?> name) {
        return new CompilationEvents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompilationEvents where(Condition condition) {
        return new CompilationEvents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompilationEvents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompilationEvents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompilationEvents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompilationEvents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompilationEvents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompilationEvents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompilationEvents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompilationEvents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompilationEvents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
