/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.practicum.explorewithme.jooq.Keys;
import ru.practicum.explorewithme.jooq.Public;
import ru.practicum.explorewithme.jooq.tables.Categories.CategoriesPath;
import ru.practicum.explorewithme.jooq.tables.CompilationEvents.CompilationEventsPath;
import ru.practicum.explorewithme.jooq.tables.Compilations.CompilationsPath;
import ru.practicum.explorewithme.jooq.tables.Locations.LocationsPath;
import ru.practicum.explorewithme.jooq.tables.Requests.RequestsPath;
import ru.practicum.explorewithme.jooq.tables.Users.UsersPath;
import ru.practicum.explorewithme.jooq.tables.records.EventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Events extends TableImpl<EventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.events</code>
     */
    public static final Events EVENTS = new Events();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsRecord> getRecordType() {
        return EventsRecord.class;
    }

    /**
     * The column <code>public.events.id</code>.
     */
    public final TableField<EventsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.events.annotation</code>.
     */
    public final TableField<EventsRecord, String> ANNOTATION = createField(DSL.name("annotation"), SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>public.events.category_id</code>.
     */
    public final TableField<EventsRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.events.confirmed_requests</code>.
     */
    public final TableField<EventsRecord, Integer> CONFIRMED_REQUESTS = createField(DSL.name("confirmed_requests"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.events.created_on</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.events.description</code>.
     */
    public final TableField<EventsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(7000).nullable(false), this, "");

    /**
     * The column <code>public.events.event_date</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> EVENT_DATE = createField(DSL.name("event_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.events.initiator_id</code>.
     */
    public final TableField<EventsRecord, Long> INITIATOR_ID = createField(DSL.name("initiator_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.events.location_id</code>.
     */
    public final TableField<EventsRecord, Long> LOCATION_ID = createField(DSL.name("location_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.events.paid</code>.
     */
    public final TableField<EventsRecord, Boolean> PAID = createField(DSL.name("paid"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.events.participant_limit</code>.
     */
    public final TableField<EventsRecord, Integer> PARTICIPANT_LIMIT = createField(DSL.name("participant_limit"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.events.published_on</code>.
     */
    public final TableField<EventsRecord, LocalDateTime> PUBLISHED_ON = createField(DSL.name("published_on"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.events.request_moderation</code>.
     */
    public final TableField<EventsRecord, Boolean> REQUEST_MODERATION = createField(DSL.name("request_moderation"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.events.state</code>.
     */
    public final TableField<EventsRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(31).nullable(false), this, "");

    /**
     * The column <code>public.events.title</code>.
     */
    public final TableField<EventsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>public.events.views</code>.
     */
    public final TableField<EventsRecord, Integer> VIEWS = createField(DSL.name("views"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private Events(Name alias, Table<EventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Events(Name alias, Table<EventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.events</code> table reference
     */
    public Events(String alias) {
        this(DSL.name(alias), EVENTS);
    }

    /**
     * Create an aliased <code>public.events</code> table reference
     */
    public Events(Name alias) {
        this(alias, EVENTS);
    }

    /**
     * Create a <code>public.events</code> table reference
     */
    public Events() {
        this(DSL.name("events"), null);
    }

    public <O extends Record> Events(Table<O> path, ForeignKey<O, EventsRecord> childPath, InverseForeignKey<O, EventsRecord> parentPath) {
        super(path, childPath, parentPath, EVENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EventsPath extends Events implements Path<EventsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EventsPath(Table<O> path, ForeignKey<O, EventsRecord> childPath, InverseForeignKey<O, EventsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EventsPath(Name alias, Table<EventsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EventsPath as(String alias) {
            return new EventsPath(DSL.name(alias), this);
        }

        @Override
        public EventsPath as(Name alias) {
            return new EventsPath(alias, this);
        }

        @Override
        public EventsPath as(Table<?> alias) {
            return new EventsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EventsRecord, Long> getIdentity() {
        return (Identity<EventsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EventsRecord> getPrimaryKey() {
        return Keys.PK_EVENTS;
    }

    @Override
    public List<ForeignKey<EventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EVENTS__FK_EVENTS_CATEGORY, Keys.EVENTS__FK_EVENTS_INITIATOR, Keys.EVENTS__FK_EVENTS_LOCATION);
    }

    private transient CategoriesPath _categories;

    /**
     * Get the implicit join path to the <code>public.categories</code> table.
     */
    public CategoriesPath categories() {
        if (_categories == null)
            _categories = new CategoriesPath(this, Keys.EVENTS__FK_EVENTS_CATEGORY, null);

        return _categories;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.EVENTS__FK_EVENTS_INITIATOR, null);

        return _users;
    }

    private transient LocationsPath _locations;

    /**
     * Get the implicit join path to the <code>public.locations</code> table.
     */
    public LocationsPath locations() {
        if (_locations == null)
            _locations = new LocationsPath(this, Keys.EVENTS__FK_EVENTS_LOCATION, null);

        return _locations;
    }

    private transient CompilationEventsPath _compilationEvents;

    /**
     * Get the implicit to-many join path to the
     * <code>public.compilation_events</code> table
     */
    public CompilationEventsPath compilationEvents() {
        if (_compilationEvents == null)
            _compilationEvents = new CompilationEventsPath(this, null, Keys.COMPILATION_EVENTS__FK_COMPILATION_EVENTS_EVENT.getInverseKey());

        return _compilationEvents;
    }

    private transient RequestsPath _requests;

    /**
     * Get the implicit to-many join path to the <code>public.requests</code>
     * table
     */
    public RequestsPath requests() {
        if (_requests == null)
            _requests = new RequestsPath(this, null, Keys.REQUESTS__FK_REQUESTS_EVENT.getInverseKey());

        return _requests;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.compilations</code> table
     */
    public CompilationsPath compilations() {
        return compilationEvents().compilations();
    }

    @Override
    public Events as(String alias) {
        return new Events(DSL.name(alias), this);
    }

    @Override
    public Events as(Name alias) {
        return new Events(alias, this);
    }

    @Override
    public Events as(Table<?> alias) {
        return new Events(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(String name) {
        return new Events(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Name name) {
        return new Events(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Table<?> name) {
        return new Events(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Condition condition) {
        return new Events(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
