/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.practicum.explorewithme.jooq.Keys;
import ru.practicum.explorewithme.jooq.Public;
import ru.practicum.explorewithme.jooq.tables.Events.EventsPath;
import ru.practicum.explorewithme.jooq.tables.records.LocationsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Locations extends TableImpl<LocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.locations</code>
     */
    public static final Locations LOCATIONS = new Locations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LocationsRecord> getRecordType() {
        return LocationsRecord.class;
    }

    /**
     * The column <code>public.locations.id</code>.
     */
    public final TableField<LocationsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.locations.lat</code>.
     */
    public final TableField<LocationsRecord, Double> LAT = createField(DSL.name("lat"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.locations.lon</code>.
     */
    public final TableField<LocationsRecord, Double> LON = createField(DSL.name("lon"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Locations(Name alias, Table<LocationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Locations(Name alias, Table<LocationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.locations</code> table reference
     */
    public Locations(String alias) {
        this(DSL.name(alias), LOCATIONS);
    }

    /**
     * Create an aliased <code>public.locations</code> table reference
     */
    public Locations(Name alias) {
        this(alias, LOCATIONS);
    }

    /**
     * Create a <code>public.locations</code> table reference
     */
    public Locations() {
        this(DSL.name("locations"), null);
    }

    public <O extends Record> Locations(Table<O> path, ForeignKey<O, LocationsRecord> childPath, InverseForeignKey<O, LocationsRecord> parentPath) {
        super(path, childPath, parentPath, LOCATIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LocationsPath extends Locations implements Path<LocationsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LocationsPath(Table<O> path, ForeignKey<O, LocationsRecord> childPath, InverseForeignKey<O, LocationsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LocationsPath(Name alias, Table<LocationsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LocationsPath as(String alias) {
            return new LocationsPath(DSL.name(alias), this);
        }

        @Override
        public LocationsPath as(Name alias) {
            return new LocationsPath(alias, this);
        }

        @Override
        public LocationsPath as(Table<?> alias) {
            return new LocationsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<LocationsRecord, Long> getIdentity() {
        return (Identity<LocationsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LocationsRecord> getPrimaryKey() {
        return Keys.PK_LOCATIONS;
    }

    private transient EventsPath _events;

    /**
     * Get the implicit to-many join path to the <code>public.events</code>
     * table
     */
    public EventsPath events() {
        if (_events == null)
            _events = new EventsPath(this, null, Keys.EVENTS__FK_EVENTS_LOCATION.getInverseKey());

        return _events;
    }

    @Override
    public Locations as(String alias) {
        return new Locations(DSL.name(alias), this);
    }

    @Override
    public Locations as(Name alias) {
        return new Locations(alias, this);
    }

    @Override
    public Locations as(Table<?> alias) {
        return new Locations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Locations rename(String name) {
        return new Locations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Locations rename(Name name) {
        return new Locations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Locations rename(Table<?> name) {
        return new Locations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Locations where(Condition condition) {
        return new Locations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Locations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Locations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Locations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Locations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Locations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Locations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Locations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Locations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Locations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
