/*
 * This file is generated by jOOQ.
 */
package ru.explorewithme.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.explorewithme.jooq.tables.Compilations;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompilationsRecord extends UpdatableRecordImpl<CompilationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.compilations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.compilations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.compilations.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.compilations.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.compilations.pinned</code>.
     */
    public void setPinned(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.compilations.pinned</code>.
     */
    public Boolean getPinned() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompilationsRecord
     */
    public CompilationsRecord() {
        super(Compilations.COMPILATIONS);
    }

    /**
     * Create a detached, initialised CompilationsRecord
     */
    public CompilationsRecord(Long id, String title, Boolean pinned) {
        super(Compilations.COMPILATIONS);

        setId(id);
        setTitle(title);
        setPinned(pinned);
        resetChangedOnNotNull();
    }
}
