/*
 * This file is generated by jOOQ.
 */
package ru.explorewithme.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.explorewithme.jooq.tables.CompilationEvents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompilationEventsRecord extends UpdatableRecordImpl<CompilationEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.compilation_events.compilation_id</code>.
     */
    public void setCompilationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.compilation_events.compilation_id</code>.
     */
    public Long getCompilationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.compilation_events.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.compilation_events.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompilationEventsRecord
     */
    public CompilationEventsRecord() {
        super(CompilationEvents.COMPILATION_EVENTS);
    }

    /**
     * Create a detached, initialised CompilationEventsRecord
     */
    public CompilationEventsRecord(Long compilationId, Long eventId) {
        super(CompilationEvents.COMPILATION_EVENTS);

        setCompilationId(compilationId);
        setEventId(eventId);
        resetChangedOnNotNull();
    }
}
