/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.practicum.explorewithme.jooq.ru.explorewithme.jooq.tables.Locations;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LocationsRecord extends UpdatableRecordImpl<LocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.locations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.locations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.locations.lat</code>.
     */
    public void setLat(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.locations.lat</code>.
     */
    public Double getLat() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.locations.lon</code>.
     */
    public void setLon(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.locations.lon</code>.
     */
    public Double getLon() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationsRecord
     */
    public LocationsRecord() {
        super(Locations.LOCATIONS);
    }

    /**
     * Create a detached, initialised LocationsRecord
     */
    public LocationsRecord(Long id, Double lat, Double lon) {
        super(Locations.LOCATIONS);

        setId(id);
        setLat(lat);
        setLon(lon);
        resetChangedOnNotNull();
    }
}
