server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

shareit-server:
  url: "http://localhost:8080"

---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/stat
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://stats-db:5432/stat
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
