server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://stats-db:5432/postgres
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true