CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app           VARCHAR(255)                             NOT NULL,
    uri           VARCHAR(255)                             NOT NULL,
    ip            VARCHAR(35)                              NOT NULL,
    timestamp     TIMESTAMP                                NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS view_stats
(
    app           VARCHAR(255)                            NOT NULL,
    uri           VARCHAR(255)                            NOT NULL,
    hit           INTEGER                                 NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (app, uri)
);