/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.practicum.explorewithme.jooq.tables.Comments;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommentsRecord extends UpdatableRecordImpl<CommentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.comments.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.comments.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.comments.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.comments.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.comments.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.comments.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.comments.event_id</code>.
     */
    public void setEventId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.comments.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.comments.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.comments.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.comments.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.comments.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentsRecord
     */
    public CommentsRecord() {
        super(Comments.COMMENTS);
    }

    /**
     * Create a detached, initialised CommentsRecord
     */
    public CommentsRecord(Long id, String content, LocalDateTime created, Long eventId, Long authorId, String status) {
        super(Comments.COMMENTS);

        setId(id);
        setContent(content);
        setCreated(created);
        setEventId(eventId);
        setAuthorId(authorId);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
