/*
 * This file is generated by jOOQ.
 */
package ru.practicum.explorewithme.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.practicum.explorewithme.jooq.tables.Events;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.events.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.events.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.events.annotation</code>.
     */
    public void setAnnotation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.events.annotation</code>.
     */
    public String getAnnotation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.events.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.events.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.events.confirmed_requests</code>.
     */
    public void setConfirmedRequests(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.events.confirmed_requests</code>.
     */
    public Integer getConfirmedRequests() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.events.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.events.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.events.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.events.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.events.event_date</code>.
     */
    public void setEventDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.events.event_date</code>.
     */
    public LocalDateTime getEventDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.events.initiator_id</code>.
     */
    public void setInitiatorId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.events.initiator_id</code>.
     */
    public Long getInitiatorId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.events.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.events.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.events.paid</code>.
     */
    public void setPaid(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.events.paid</code>.
     */
    public Boolean getPaid() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.events.participant_limit</code>.
     */
    public void setParticipantLimit(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.events.participant_limit</code>.
     */
    public Integer getParticipantLimit() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.events.published_on</code>.
     */
    public void setPublishedOn(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.events.published_on</code>.
     */
    public LocalDateTime getPublishedOn() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.events.request_moderation</code>.
     */
    public void setRequestModeration(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.events.request_moderation</code>.
     */
    public Boolean getRequestModeration() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.events.state</code>.
     */
    public void setState(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.events.state</code>.
     */
    public String getState() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.events.title</code>.
     */
    public void setTitle(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.events.title</code>.
     */
    public String getTitle() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.events.views</code>.
     */
    public void setViews(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.events.views</code>.
     */
    public Long getViews() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(Long id, String annotation, Long categoryId, Integer confirmedRequests, LocalDateTime createdOn, String description, LocalDateTime eventDate, Long initiatorId, Long locationId, Boolean paid, Integer participantLimit, LocalDateTime publishedOn, Boolean requestModeration, String state, String title, Long views) {
        super(Events.EVENTS);

        setId(id);
        setAnnotation(annotation);
        setCategoryId(categoryId);
        setConfirmedRequests(confirmedRequests);
        setCreatedOn(createdOn);
        setDescription(description);
        setEventDate(eventDate);
        setInitiatorId(initiatorId);
        setLocationId(locationId);
        setPaid(paid);
        setParticipantLimit(participantLimit);
        setPublishedOn(publishedOn);
        setRequestModeration(requestModeration);
        setState(state);
        setTitle(title);
        setViews(views);
        resetChangedOnNotNull();
    }
}
