jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: service
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres is up" && break
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Apply schema.sql
        run: |
          psql -h localhost -U postgres -d service -f service-server/src/main/resources/schema.sql
        env:
          PGPASSWORD: 1234

      - name: Build project
        run: mvn clean install